g = 9.81;
m = 1; 
Cd = 0.5; 
rho = 1.2; 
A = 0.1; 
v0 = input('Ingrese la velocidad inicial (m/s): '); 
theta = input('Ingrese el ángulo de salida (grados): '); 
theta_rad = theta * pi / 180; Fd = 0.5 * Cd * rho * A; 
dt = 0.01;
t_max = 10; 
x = 0;
y = 0; 
vx = v0 * cos(theta_rad); 
vy = v0 * sin(theta_rad); 
t = 0;
figure;
while t < t_max vx = vx - Fd * vx * dt / m;
vy = vy - g * dt - Fd * vy * dt / m; 
x = x + vx * dt; 
y = y + vy * dt;
plot(x, y, 'b-'); 
hold on;
plot(x, y, 'ro'); 
axis equal; 
xlabel('X (m)'); 
ylabel('Y (m)'); 
title('Trayectoria del proyectil'); 
drawnow;
t = t + dt;
if y < 0 break; 
end end
